kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
- deployment.yaml
- service.yaml
# - hpa.yaml

configMapGenerator:
- files:
  - config/logback.xml
  name: am-logback

generatorOptions:
  disableNameSuffixHash: true
labels:
- includeSelectors: true
  pairs:
    app: am
    app.kubernetes.io/component: am
    app.kubernetes.io/instance: am
    app.kubernetes.io/name: am
    app.kubernetes.io/part-of: forgerock
    tier: middle
