#Patch DS idrepo
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ds-idrepo
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: ds
        resources:
          requests:
            memory: 1366Mi
            cpu: 500m
          limits:
            memory: 1366Mi
      initContainers:
      - name: init
        resources:
          requests:
            memory: 1366Mi
            cpu: 500m
          limits:
            memory: 1366Mi
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        pv.beta.kubernetes.io/gid: "0"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
      storageClassName: fast