pipeline:
  name: Ping
  identifier: Ping
  projectIdentifier: IDA
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: Ping
        build: <+input>
  stages:
    - stage:
        name: CI
        identifier: CI
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.k8s
              namespace: api
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: FetchBinaries
                  identifier: Run_1
                  spec:
                    connectorRef: account.harnessImage
                    image: gtbanf1979/maven:v1
                    shell: Sh
                    command: |-
                      curl -k https://192.168.1.83:8443/repository/adhoc/PING/AM-7.5.1.zip -O
                      curl -k https://192.168.1.83:8443/repository/adhoc/PING/Amster-7.5.1.zip -O
                      curl -k https://192.168.1.83:8443/repository/adhoc/PING/DS-7.5.2.zip -O

                      pwd
                      ls -la .

                      #Unzip Ping Artifacts
                      unzip -q AM-7.5.1.zip
                      unzip -q Amster-7.5.1.zip
                      unzip -q DS-7.5.2.zip

                      #Copy Dockerfile

                      #DS-Empty
                      #cp docker/7.5/DS-Empty/Dockerfile /harness/opendj/samples/docker/

                      #Amster-Base
                      #cp docker/7.5/Amster-Base/Dockerfile /harness/amster/samples/docker/

                      #AM
                      #cp docker/7.5/AM/AM-EMPTY/Dockerfile /harness/openam/samples/docker/images/am-empty/
                      #cp docker/7.5/AM/AM-BASE/Dockerfile /harness/openam/samples/docker/images/am-base/
                      #cp docker/7.5/AM/AM-CDK/Dockerfile /harness/openam/samples/docker/images/am-cdk/
                    resources:
                      limits:
                        memory: 8Gi
                        cpu: 2
              - step:
                  name: Nexus
                  identifier: Nexus
                  template:
                    templateRef: Nexus
                    versionLabel: v0.1.0
                    gitBranch: main
                    templateInputs:
                      type: BuildAndPushDockerRegistry
                      spec:
                        tags: <+input>
                        dockerfile: <+input>
                        context: <+input>
  delegateSelectors:
    - kubernetes-delegate-account
