kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
- job.yaml
labels:
- includeSelectors: true
  pairs:
    app: amster
    app.kubernetes.io/component: am
    app.kubernetes.io/instance: amster
    app.kubernetes.io/name: amster
    app.kubernetes.io/part-of: forgerock
