kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

configurations:
- kustomizeConfig.yaml


# The env vars below can be passed into a pod using the envFrom pod spec.
# These global variables can be used to parameterize your deployments.
# The FQDN and URLs here should match your ingress definitions
configMapGenerator:
- literals:
  - FQDN=default.iam.example.com
  - AM_URL=/am
  - AM_ADMIN_URL=/am/ui-admin/
  - IDM_ADMIN_URL=/admin
  - IDM_UPLOAD_URL=/upload
  - IDM_EXPORT_URL=/export
  - PLATFORM_ADMIN_URL=/platform
  - IDM_REST_URL=/openidm
  - ENDUSER_UI_URL=/enduser
  - LOGIN_UI_URL=/login/#/service/Login
  - PLATFORM_UI_IS_FRAAS="false" # Identity Cloud functionality is disabled in the platform
  - FRAAS_LOGGING_URL="" # Location of Identity Cloud log api key service for the deployment
  - ENDUSER_CLIENT_ID=end-user-ui
  - ADMIN_CLIENT_ID=idm-admin-ui
  - THEME=default
  - AM_STORES_CTS_SERVERS="ds-cts-0.ds-cts:1636"
  - AM_STORES_USER_SERVERS="ds-idrepo-0.ds-idrepo:1636"
  - AM_SERVER_FQDN="$(FQDN)"
  - AUTORESTORE_FROM_DSBACKUP="false" # Set to "true" to enable DS auto restore from backup. See documentation
  - DSBACKUP_DIRECTORY="" # Ex. gs://bucket | s3://bucket | az://container
  - DSBACKUP_HOSTS="ds-cts-2,ds-idrepo-2" # Server used to create backup. Should match hosts var configured in ds-backup.sh.
  - DISASTER_RECOVERY_ID="initial-restore" # Set the Disaster Recover to unique value when restoring from a previous backup.
  - CERT_ISSUER="default-issuer" # cert manager issuer. Patch with letsencrypt-prod for LE SSL certs.
  - ENABLE_WORKFORCE="true" # Enables the platform-ui Workforce functionality. This is the supported UI mode going forwards.
  name: platform-config

generatorOptions:
  disableNameSuffixHash: true

# The variables defined below can be referenced in resources using the syntax $(VARIABLE)
vars:
- fieldref:
    fieldpath: data.FQDN
  name: FQDN
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: platform-config
- fieldref:
    fieldpath: data.CERT_ISSUER
  name: CERT_ISSUER
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: platform-config
