#Patch DS CTS
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ds-cts
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: ds
        resources:
          requests:
            memory: 11Gi
            cpu: 8000m
          limits:
            memory: 11Gi
      initContainers:
      - name: init
        resources:
          requests:
            memory: 11Gi
            cpu: 8000m
          limits:
            memory: 11Gi
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        pv.beta.kubernetes.io/gid: "0"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 500Gi
      storageClassName: fast