kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
#namespace: smoke
resources:
- perf-test-job.yaml
secretGenerator:
- files:
  - key.json
  name: gcs-key
labels:
- includeSelectors: true
  pairs:
    app: gatling
