apiVersion: batch/v1
kind: CronJob
metadata:
  name: ds-idrepo-snapshot
spec:
  schedule: "*/10 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: ds-idrepo-snapshot
              env:
                - name: PURGE_DELAY
                  value: "-1 hour"
