resources:
- ../../base/kustomizeConfig
- ../../base/ingress

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/part-of: forgerock
patches:
- patch: |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: platform-config
    data:
      FQDN: "nightly.eng.forgeops.com"
      CERT_ISSUER: letsencrypt-prod
