
resources:
- deployment.yaml
- service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: git-server
    app.kubernetes.io/instance: git-server
    app.kubernetes.io/name: git-server
    app.kubernetes.io/part-of: forgerock
