resources:
- ds-idrepo.yaml

configurations:
- kustomizeConfig.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: directory
    app.kubernetes.io/instance: ds-idrepo
    app.kubernetes.io/name: ds
    app.kubernetes.io/part-of: forgerock
