apiVersion: v1
kind: Service
metadata:
  name: ds
  labels:
    app.kubernetes.io/instance: ds-idrepo
    app.kubernetes.io/name: ds
    app.kubernetes.io/part-of: forgerock
spec:
  clusterIP: None
  ports:
  - name: tcp-admin
    port: 4444
    protocol: TCP
    targetPort: 4444
  - name: tcp-ldap
    port: 1389
    protocol: TCP
    targetPort: 1389
  - name: tcp-ldaps
    port: 1636
    protocol: TCP
    targetPort: 1636
  - name: tcp-replication
    port: 8989
    protocol: TCP
    targetPort: 8989
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: ds-idrepo
    app.kubernetes.io/name: ds
